### ISSUE TITLE
Question regarding the inputs

### ISSUE THREAD

**Issue by aviaisr** [mattroz/mobilenet_segmentation#1]
Hi,
I would like to train your model on my own dataset.

GENERAL: Can you please add more instructions to the 'read me' file regarding the training process?

MY QUESION IS:
* I got the h5 file downloaded to 
.\keras\models\mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.0_224_no_top.h5

when I'm trying to run train.py the code fails with loading the model:

b'C:\\Users\\aviai\\.keras\\models\\mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.0_224_no_top.h5'
Traceback (most recent call last):
  File "train.py", line 46, in <module>
    compile=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\saving.py", line 551, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\saving.py", line 239, in _deserialize_model
    model_config = h5dict['model_config']
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\io_utils.py", line 318, in __getitem__
    raise ValueError('Cannot create group in read-only mode.')
ValueError: Cannot create group in read-only mode.

**Comment by mattroz** [comment]
Hey, @aviaisr
Could you show me how exactly you're trying to execute ```train.py``` script?
Did you change some source code?

The point is that  ```Cannot create group in read-only mode``` error shows up when your weights are not belong to the current model's architecture.

**Comment by mattroz** [comment]
As far as I understand your question is how to integrate your own model into this pipeline?
